### ISSUE TITLE
フィルターの追加

### ISSUE THREAD

**Issue by YIPG** [lacolaco/angular-after-tutorial#2]
https://gitbook.lacolaco.net/angular-after-tutorial/season-1-the-first-refactoring/forms-and-state

フィルターフォームについてですが、moduleにReactiveFormsModuleを追加しないとエラーが出ます。

デフォルトのng newではReactiveFormsModuleは生成されないので、説明を追加するべきだと思いますがどうでしょうか？（お忙しいようならわたしが該当パートを書いてPR出します！）

**Comment by lacolaco** [comment]
@YIPG ご報告ありがとうございます！近日中に加筆修正しておきます！
修正完了したらこのIssueをクローズします

**Comment by lacolaco** [comment]
対応しました。
